apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
        - name: my-container
          image: kustomize edit set image udagram-reverseproxy=haitruong1001/udagram-reverseproxy:latest
          ports:
            - containerPort: 8080
