apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    app: uudagram-frontend
spec:
  selector:
    app: udagram-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
