name: build docker image

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-reverseproxy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Kubeconfig Auth
        run: |
          aws eks update-kubeconfig --name udagram-pro3 --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          cd ./udagram-reverseproxy/k8s
          kustomize edit set image udagram-reverseproxy=haitruong1001/udagram-reverseproxy:latest
          kustomize build | kubectl apply -f -